--- name:default
max_angular_speed: 0.3141592653589793
max_speed: 1.5
min_speed: 0.5
straight_duration: 5.0
turn_duration: 5.0
--- name:slow
max_speed: 0.5
min_speed: 0
--- name:fast
max_speed: 4
min_speed: 2
